// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

/*
Firebase configuration file lib\firebase_options.dart generated successfully with the following Firebase apps:

Platform  Firebase App Id
web       1:1043515732452:web:71a798ca1d81b3dd4117f1
android   1:1043515732452:android:5c30188ef7ff9f4f4117f1
*/

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9-esDBM9g_gHtgxPvyQFT8t3kmbpzEwY',
    appId: '1:1043515732452:android:5c30188ef7ff9f4f4117f1',
    messagingSenderId: '1043515732452',
    projectId: 'where-in-vit-2497e',
    storageBucket: 'where-in-vit-2497e.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc3Dgh4YcWBNpDRdyv60gRN9vO0oLvygI',
    appId: '1:1043515732452:web:71a798ca1d81b3dd4117f1',
    messagingSenderId: '1043515732452',
    projectId: 'where-in-vit-2497e',
    authDomain: 'where-in-vit-2497e.firebaseapp.com',
    storageBucket: 'where-in-vit-2497e.appspot.com',
    measurementId: 'G-5JFJBQZ1WC',
  );
}
